version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops_network

  devops_project:
    image: tijaniboujdaria/tijaniboujdaria_5ia_tijaniwalidgroup_devops_project:1.0.0
    container_name: devops_project
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - devops_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

networks:
  devops_network:

volumes:
  mysql_data:
